[package]
name = "substrate-chain-spec-derive"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "0.1.3"
proc-macro2 = "0.4"
quote = "0.6.12"
syn = "^0.15.30"

[dev-dependencies]

